### ISSUE TITLE
Please add last selected gameobject state as well

### ISSUE THREAD

**Issue by sathyarajshetigar** [brunomikoski/SceneKeeper#1]
Is it possible to cache the last selected gameObject in the Hierarchy!. that would be really cool

**Comment by brunomikoski** [comment]
Sure! I will do that! 

But what is your opinion to multiple selected game objects at the same time?

My idea for something like this would be the last selection before entering in play mode, but what do you think @sathyarajshetigar ?

**Comment by sathyarajshetigar** [comment]
Yes, the last selected gameObject when entering the play mode and closing the scene.
We can try implementing both and see what suits everyone. if both can be achieved maybe  give an option to choose

**Comment by brunomikoski** [comment]
The problem with doing when closing the scene is, you always gonna end up with multiple objects selected, and maybe this will be messy? Either way, I'm gonna add the one that works properly with the `ExitingEditMode`.

**Comment by sathyarajshetigar** [comment]
Awesome.

**Comment by brunomikoski** [comment]
Done! :)

**Comment by sathyarajshetigar** [comment]
Tried 0.0.3 Did not work as expected.
Flow.
Opened the scene
Selected an object
Closed and reopened the scene
the previously selected object was not selected

**Comment by brunomikoski** [comment]
> Tried 0.0.3 Did not work as expected.
> Flow.
> Opened the scene
> Selected an object
> Closed and reopened the scene
> the previously selected object was not selected

Yeah the solution that I added in 0.0.3 its only for when you are entering play mode! 
But I see what you want now, should be easy to implement it! I will do it tonight.

**Comment by brunomikoski** [comment]
Okay finally found a proper way of doing it! Give it a try on version 0.0.4 @sathyarajshetigar and let me know if works.
