### ISSUE TITLE
New hierarchy window pops up in batchmode

### ISSUE THREAD

**Issue by IJsLauw** [brunomikoski/SceneKeeper#12]
A hierarchy window pops up when building in batchmode using commandline. That's very anoying when you're running something like Jenkins to do that on servers or co-workers computers :)

It made me delete your otherwise useful asset from our projects.

**Comment by brunomikoski** [comment]
Fixed on the new release:

https://github.com/brunomikoski/SceneKeeper/releases/tag/v0.1.4
