### ISSUE TITLE
Keep Hierarchy between restarts

### ISSUE THREAD

**Issue by Thane5** [brunomikoski/SceneKeeper#6]
Simple suggestion: keep the hierarchy layout between Editor restarts for an even more constistent experience.

**Comment by brunomikoski** [comment]
That's a good idea! I'm gonna add into the next release :)

**Comment by brunomikoski** [comment]
Done! Implemented on the release 0.1.1: https://github.com/brunomikoski/SceneKeeper/releases/tag/v0.1.1
